# TCL File Generated by Component Editor 18.0
# Wed Apr 17 21:28:04 CDT 2019
# DO NOT MODIFY


# 
# SDRAM_Master_Core "SDRAM Master Core" v1.3
#  2019.04.17.21:28:04
# Allows FPGA to serve as Master to control SDRAM.
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module SDRAM_Master_Core
# 
set_module_property DESCRIPTION "Allows FPGA to serve as Master to control SDRAM."
set_module_property NAME SDRAM_Master_Core
set_module_property VERSION 1.3
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Final Project"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "SDRAM Master Core"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL SDRAM_Master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file SDRAM_Master.sv SYSTEM_VERILOG PATH SDRAM_Master.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL SDRAM_Master
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file SDRAM_Master.sv SYSTEM_VERILOG PATH SDRAM_Master.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 50000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock CLK
set_interface_property avalon_master associatedReset RESET
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 0
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master AVL_ADDR address Output 32
add_interface_port avalon_master AVL_BYTE_EN byteenable Output 4
add_interface_port avalon_master AVL_CS chipselect Output 1
add_interface_port avalon_master AVL_READ read Output 1
add_interface_port avalon_master AVL_READDATA readdata Input 32
add_interface_port avalon_master AVL_WRITE write Output 1
add_interface_port avalon_master AVL_WRITEDATA writedata Output 32
add_interface_port avalon_master AVL_WAITREQ waitrequest Input 1
add_interface_port avalon_master AVL_RDV readdatavalid Input 1


# 
# connection point OUTSIDE_DATA
# 
add_interface OUTSIDE_DATA conduit end
set_interface_property OUTSIDE_DATA associatedClock CLK
set_interface_property OUTSIDE_DATA associatedReset ""
set_interface_property OUTSIDE_DATA ENABLED true
set_interface_property OUTSIDE_DATA EXPORT_OF ""
set_interface_property OUTSIDE_DATA PORT_NAME_MAP ""
set_interface_property OUTSIDE_DATA CMSIS_SVD_VARIABLES ""
set_interface_property OUTSIDE_DATA SVD_ADDRESS_GROUP ""

add_interface_port OUTSIDE_DATA TL_READ tl_read Input 1
add_interface_port OUTSIDE_DATA TL_ADDR tl_addr Input 32
add_interface_port OUTSIDE_DATA TL_WRITE tl_write Input 1
add_interface_port OUTSIDE_DATA TL_WRITEDATA tl_writedata Input 32
add_interface_port OUTSIDE_DATA TL_READDATA tl_readdata Output 32
add_interface_port OUTSIDE_DATA TL_RDV tl_rdv Output 1

